---
galaxy_info:
  author: Malaber
  description: Deploy webhooker and manage webhooker project definitions.
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - all

dependencies: []
