---
webhooker_deploy_path: /srv/webhooker
webhooker_compose_project_name: webhooker

webhooker_config_dir: /srv/webhooker/projects
webhooker_env_dir: /srv/webhooker/env
webhooker_state_dir: /srv/webhooker/runtime/state
webhooker_wake_dir: /srv/webhooker/runtime/wake

webhooker_collection_version: "0.3.20"
webhooker_image: ghcr.io/malaber/webhooker/webhooker:{{ webhooker_collection_version }}
webhooker_api_bind_address: 127.0.0.1
webhooker_api_port: 9100
webhooker_traefik_enabled: false
webhooker_traefik_network: system_traefik_external
webhooker_traefik_certresolver: letsencrypt
webhooker_api_hostname: ""
webhooker_api_router_name: webhooker-api
webhooker_api_service_name: webhooker-api
webhooker_worker_sleep_seconds: 60
webhooker_container_uid: "1000"
webhooker_container_gid: "1000"
webhooker_worker_group_add: []

webhooker_env: {}
webhooker_projects: []
webhooker_worker_extra_mounts: []
webhooker_managed_directories: []
webhooker_managed_files: []
webhooker_secret_env_files: []

webhooker_compose_pull: true
